---
- name: Check disk usage
  hosts: all
  tasks:
    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        var: disk_usage.stdout_lines
