---
- name: Check OS version of Linux hosts
  hosts: wfm_app_servers
  gather_facts: true
  tasks:
    - name: Display OS version
      debug:
        msg: "The OS version of {{ inventory_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_version }}"
